# Generated by Django 5.2.1 on 2025-10-10 07:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('vaccination_usage', models.PositiveIntegerField(default=0)),
                ('room_measurement_usage', models.PositiveIntegerField(default=0)),
                ('budget_calculator_usage', models.PositiveIntegerField(default=0)),
                ('pdf_downloads', models.PositiveIntegerField(default=0)),
                ('calendar_integrations', models.PositiveIntegerField(default=0)),
                ('broilers_count', models.PositiveIntegerField(default=0)),
                ('layers_count', models.PositiveIntegerField(default=0)),
                ('sasso_kroilers_count', models.PositiveIntegerField(default=0)),
                ('top_countries', models.JSONField(blank=True, default=list)),
                ('top_regions', models.JSONField(blank=True, default=list)),
                ('mobile_usage', models.PositiveIntegerField(default=0)),
                ('tablet_usage', models.PositiveIntegerField(default=0)),
                ('desktop_usage', models.PositiveIntegerField(default=0)),
                ('google_calendar', models.PositiveIntegerField(default=0)),
                ('outlook_calendar', models.PositiveIntegerField(default=0)),
                ('apple_calendar', models.PositiveIntegerField(default=0)),
                ('ics_downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frontend Analytics',
                'verbose_name_plural': 'Frontend Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsageEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(choices=[('vaccination', 'Vaccination Scheduler'), ('roomMeasurement', 'Room Measurement'), ('budgetCalculator', 'Budget Calculator'), ('pdfDownloader', 'PDF Downloader')], max_length=50)),
                ('session_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('view', 'View'), ('calculate', 'Calculate'), ('download', 'Download'), ('export', 'Export'), ('calendar_add', 'Add to Calendar'), ('email_send', 'Email Send')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=20)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tool_name', 'timestamp'], name='analytics_t_tool_na_ecb79d_idx'), models.Index(fields=['session_id'], name='analytics_t_session_850c00_idx'), models.Index(fields=['country'], name='analytics_t_country_2d209b_idx'), models.Index(fields=['device_type'], name='analytics_t_device__3709bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSubmission',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('poultry_type', models.CharField(choices=[('broilers', 'Broilers'), ('layers', 'Layers / Pullets'), ('sasso/kroilers', 'Sasso / Kroilers')], max_length=50)),
                ('arrival_date', models.DateField()),
                ('batch_name', models.CharField(default='Batch 1', max_length=100)),
                ('batch_size', models.PositiveIntegerField(default=1000)),
                ('vaccination_schedule', models.JSONField(default=list)),
                ('total_vaccinations', models.PositiveIntegerField(default=0)),
                ('estimated_sale_date', models.DateField()),
                ('farmer_name', models.CharField(blank=True, max_length=200)),
                ('farmer_email', models.EmailField(blank=True, max_length=254)),
                ('farmer_phone', models.CharField(blank=True, max_length=20)),
                ('farm_location', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processed', 'Processed'), ('assigned_vet', 'Veterinarian Assigned'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('assignment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_veterinarian', models.ForeignKey(blank=True, limit_choices_to={'admin_role': 'veterinarian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vaccinations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['poultry_type', 'arrival_date'], name='analytics_v_poultry_338726_idx'), models.Index(fields=['status'], name='analytics_v_status_4bbfe2_idx'), models.Index(fields=['country'], name='analytics_v_country_e13fce_idx'), models.Index(fields=['assigned_veterinarian'], name='analytics_v_assigne_1fe014_idx')],
            },
        ),
    ]
