// Calendar Service for generating calendar events and notifications
import dayjs, { Dayjs } from 'dayjs';

export interface CalendarEvent {
  id: string;
  title: string;
  description: string;
  startDate: Dayjs;
  endDate: Dayjs;
  location?: string;
  reminders?: {
    minutes: number;
    type: 'email' | 'popup' | 'both';
    message?: string;
  }[];
  category?: string;
  priority?: 'low' | 'medium' | 'high';
}

export interface VaccinationCalendarEvent extends CalendarEvent {
  vaccine: string;
  poultryType: string;
  batchName: string;
  notes?: string;
  route: string;
  age: string;
  preparationNotes?: string;
  contactInfo?: string;
  farmName?: string;
  veterinarian?: string;
}

class CalendarService {
  private generateUID(): string {
    return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}@river-poultry.com`;
  }

  // Generate .ics file content for calendar import
  generateICS(events: CalendarEvent[]): string {
    const now = dayjs().format('YYYYMMDDTHHmmss[Z]');
    
    let icsContent = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//River Poultry//Tools//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      `DTSTAMP:${now}`,
    ];

    events.forEach((event) => {
      const startDate = event.startDate.format('YYYYMMDDTHHmmss[Z]');
      const endDate = event.endDate.format('YYYYMMDDTHHmmss[Z]');
      const uid = this.generateUID();
      
      icsContent.push(
        'BEGIN:VEVENT',
        `UID:${uid}`,
        `DTSTART:${startDate}`,
        `DTEND:${endDate}`,
        `SUMMARY:${event.title}`,
        `DESCRIPTION:${event.description.replace(/\n/g, '\\n')}`,
        event.location ? `LOCATION:${event.location}` : '',
        `STATUS:CONFIRMED`,
        `TRANSP:OPAQUE`,
        `PRIORITY:${event.priority === 'high' ? '1' : event.priority === 'medium' ? '3' : '5'}`,
        event.reminders ? this.generateReminders(event.reminders, event as VaccinationCalendarEvent) : '',
        'END:VEVENT'
      );
    });

    icsContent.push('END:VCALENDAR');
    
    return icsContent.filter(line => line !== '').join('\r\n');
  }

  private generateReminders(reminders: CalendarEvent['reminders'], event: VaccinationCalendarEvent): string {
    if (!reminders || reminders.length === 0) return '';
    
    return reminders.map(reminder => {
      const message = reminder.message || this.generatePersonalizedMessage(event, reminder.minutes);
      return [
        'BEGIN:VALARM',
        'ACTION:DISPLAY',
        `TRIGGER:-PT${reminder.minutes}M`,
        `DESCRIPTION:${message}`,
        'END:VALARM'
      ].join('\r\n');
    }).join('\r\n');
  }

  private generatePersonalizedMessage(event: VaccinationCalendarEvent, minutesBefore: number): string {
    const timeText = this.getTimeText(minutesBefore);
    const preparationText = this.getPreparationText(event.vaccine, minutesBefore);
    const contactText = event.contactInfo ? `\n\n📞 Contact: ${event.contactInfo}` : '';
    const farmText = event.farmName ? `\n🏡 Farm: ${event.farmName}` : '';
    
    return `🐔 River Poultry Tools - ${event.vaccine} Vaccination${timeText}\n\n` +
           `📋 ${event.poultryType} - ${event.batchName}\n` +
           `💉 Route: ${event.route}\n` +
           `📅 Age: ${event.age}${preparationText}${farmText}${contactText}\n\n` +
           `🔗 Generated by River Poultry Tools`;
  }

  private getTimeText(minutesBefore: number): string {
    if (minutesBefore >= 1440) return ` (${Math.floor(minutesBefore / 1440)} day${Math.floor(minutesBefore / 1440) > 1 ? 's' : ''} before)`;
    if (minutesBefore >= 60) return ` (${Math.floor(minutesBefore / 60)} hour${Math.floor(minutesBefore / 60) > 1 ? 's' : ''} before)`;
    return ` (${minutesBefore} minute${minutesBefore > 1 ? 's' : ''} before)`;
  }

  private getPreparationText(vaccine: string, minutesBefore: number): string {
    if (minutesBefore >= 1440) {
      return `\n\n📝 Preparation needed:\n• Ensure vaccine is stored properly\n• Check equipment is ready\n• Plan vaccination team`;
    } else if (minutesBefore >= 60) {
      return `\n\n📝 Final preparation:\n• Remove vaccine from storage\n• Prepare injection equipment\n• Gather birds for vaccination`;
    } else {
      return `\n\n📝 Time to vaccinate!\n• Follow proper injection technique\n• Record vaccination details\n• Monitor birds post-vaccination`;
    }
  }

  private getVaccinePreparationNotes(vaccine: string): string {
    const notes: { [key: string]: string } = {
      'Newcastle Disease': 'Store at 2-8°C. Use within 2 hours of reconstitution. Administer via eye drop or drinking water.',
      'Infectious Bronchitis': 'Store at 2-8°C. Mix with clean, cool water. Ensure all birds have access to vaccine water.',
      'Gumboro Disease': 'Store at 2-8°C. Use sterile equipment. Administer via drinking water or injection.',
      'Fowl Pox': 'Store at 2-8°C. Use wing-web method. Ensure proper needle sterilization.',
      'Fowl Typhoid (1st Dose)': 'Store at 2-8°C. Mix with clean drinking water. Ensure all birds have access to vaccine water. Withhold other water sources during vaccination.',
      'Fowl Typhoid (Booster)': 'Store at 2-8°C. Administer via intramuscular injection in breast muscle or subcutaneous injection in neck. Use sterile equipment and proper injection technique.',
      'Fowl Typhoid (Production Booster)': 'Store at 2-8°C. Mix with clean drinking water. Administer during production phase. Ensure all birds have access to vaccine water.',
      'Fowl Typhoid': 'Store at 2-8°C. Administer via subcutaneous or intramuscular injection. Monitor for adverse reactions.',
      'Marek\'s Disease': 'Store at 2-8°C. Administer subcutaneously in neck. Use within 2 hours of reconstitution.',
      'Avian Influenza': 'Store at 2-8°C. Follow strict biosecurity protocols. Administer as per manufacturer instructions.'
    };
    
    return notes[vaccine] || 'Follow manufacturer instructions and consult your veterinarian for specific preparation requirements.';
  }

  // Generate Google Calendar URL
  generateGoogleCalendarURL(event: CalendarEvent): string {
    const startDate = event.startDate.format('YYYYMMDDTHHmmss[Z]');
    const endDate = event.endDate.format('YYYYMMDDTHHmmss[Z]');
    
    // Enhanced description with personalized information
    let enhancedDescription = event.description;
    if ('vaccine' in event && 'poultryType' in event) {
      const vaccinationEvent = event as VaccinationCalendarEvent;
      enhancedDescription = [
        `🐔 River Poultry Tools - Personalized Vaccination Reminder`,
        ``,
        `📋 ${vaccinationEvent.poultryType.toUpperCase()} - ${vaccinationEvent.batchName}`,
        `💉 Vaccine: ${vaccinationEvent.vaccine}`,
        `📍 Route: ${vaccinationEvent.route}`,
        `📅 Age: ${vaccinationEvent.age}`,
        `📝 Notes: ${vaccinationEvent.notes}`,
        ``,
        `🔔 You'll receive personalized reminders:`,
        `• 1 day before: Preparation checklist`,
        `• 1 hour before: Final preparation steps`,
        `• 15 minutes before: Time to vaccinate!`,
        ``,
        `🔗 Generated by River Poultry Tools`,
        `🌐 Visit: https://tools-bay-five.vercel.app`,
        `📞 Need help? Contact your veterinarian`
      ].join('\n');
    }
    
    const params = new URLSearchParams({
      action: 'TEMPLATE',
      text: event.title,
      dates: `${startDate}/${endDate}`,
      details: enhancedDescription,
      location: event.location || 'Poultry Farm',
      trp: 'false',
      sprop: 'name:River Poultry Tools|website:https://tools-bay-five.vercel.app',
      recur: 'RRULE:FREQ=YEARLY;COUNT=1'
    });

    return `https://calendar.google.com/calendar/render?${params.toString()}`;
  }

  // Generate Outlook Calendar URL
  generateOutlookCalendarURL(event: CalendarEvent): string {
    const startDate = event.startDate.format('YYYY-MM-DDTHH:mm:ss[Z]');
    const endDate = event.endDate.format('YYYY-MM-DDTHH:mm:ss[Z]');
    
    const params = new URLSearchParams({
      path: '/calendar/action/compose',
      rru: 'addevent',
      subject: event.title,
      startdt: startDate,
      enddt: endDate,
      body: event.description,
      location: event.location || ''
    });

    return `https://outlook.live.com/calendar/0/deeplink/compose?${params.toString()}`;
  }

  // Generate Apple Calendar URL (for iOS/macOS)
  generateAppleCalendarURL(event: CalendarEvent): string {
    const startDate = event.startDate.format('YYYYMMDDTHHmmss[Z]');
    const endDate = event.endDate.format('YYYYMMDDTHHmmss[Z]');
    
    const params = new URLSearchParams({
      title: event.title,
      start: startDate,
      end: endDate,
      description: event.description,
      location: event.location || ''
    });

    return `webcal://p01-calendarws.icloud.com/ca/subscribe/1/${params.toString()}`;
  }

  // Download .ics file
  downloadICS(events: CalendarEvent[], filename: string = 'vaccination-schedule.ics'): void {
    const icsContent = this.generateICS(events);
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  // Create vaccination calendar events
  createVaccinationEvents(
    vaccines: Array<{
      age: string;
      vaccine: string;
      route: string;
      notes: string;
      days?: number;
      startDay?: number;
      endDay?: number;
    }>,
    arrivalDate: Dayjs,
    poultryType: string,
    batchName: string = 'Batch 1'
  ): VaccinationCalendarEvent[] {
    return vaccines.map((vaccine, index) => {
      // Use startDay for date ranges, or days for single day, or default to arrival date
      const scheduledDate = vaccine.days 
        ? arrivalDate.add(vaccine.days - 1, 'day')
        : vaccine.startDay 
          ? arrivalDate.add(vaccine.startDay - 1, 'day')
          : arrivalDate;

      const title = `🐔 ${vaccine.vaccine} - ${poultryType.toUpperCase()}`;
      const description = [
        `🏡 Poultry Type: ${poultryType.toUpperCase()}`,
        `📦 Batch: ${batchName}`,
        `📅 Age: ${vaccine.age}`,
        `💉 Vaccine: ${vaccine.vaccine}`,
        `📍 Route: ${vaccine.route}`,
        `📝 Notes: ${vaccine.notes}`,
        '',
        `🔗 Generated by River Poultry Tools`,
        `🌐 Visit: https://tools-bay-five.vercel.app`,
        '',
        `📞 Need help? Contact your veterinarian or visit our support page.`
      ].join('\n');

      return {
        id: `vaccination-${index}-${Date.now()}`,
        title,
        description,
        startDate: scheduledDate,
        endDate: scheduledDate.add(1, 'hour'), // 1 hour duration
        location: 'Poultry Farm',
        reminders: [
          {
            minutes: 1440, // 1 day before
            type: 'both',
            message: `🐔 River Poultry Tools - ${vaccine.vaccine} Vaccination (1 day before)\n\n📋 ${poultryType.toUpperCase()} - ${batchName}\n💉 Route: ${vaccine.route}\n📅 Age: ${vaccine.age}\n\n📝 Preparation needed:\n• Ensure vaccine is stored properly\n• Check equipment is ready\n• Plan vaccination team\n\n🔗 Generated by River Poultry Tools`
          },
          {
            minutes: 60, // 1 hour before
            type: 'both',
            message: `🐔 River Poultry Tools - ${vaccine.vaccine} Vaccination (1 hour before)\n\n📋 ${poultryType.toUpperCase()} - ${batchName}\n💉 Route: ${vaccine.route}\n📅 Age: ${vaccine.age}\n\n📝 Final preparation:\n• Remove vaccine from storage\n• Prepare injection equipment\n• Gather birds for vaccination\n\n🔗 Generated by River Poultry Tools`
          },
          {
            minutes: 15, // 15 minutes before
            type: 'both',
            message: `🐔 River Poultry Tools - ${vaccine.vaccine} Vaccination (15 minutes before)\n\n📋 ${poultryType.toUpperCase()} - ${batchName}\n💉 Route: ${vaccine.route}\n📅 Age: ${vaccine.age}\n\n📝 Time to vaccinate!\n• Follow proper injection technique\n• Record vaccination details\n• Monitor birds post-vaccination\n\n🔗 Generated by River Poultry Tools`
          }
        ],
        category: 'Vaccination',
        priority: 'high',
        vaccine: vaccine.vaccine,
        poultryType,
        batchName,
        notes: vaccine.notes,
        route: vaccine.route,
        age: vaccine.age,
        preparationNotes: this.getVaccinePreparationNotes(vaccine.vaccine),
        contactInfo: 'Contact your veterinarian for support',
        farmName: 'Your Poultry Farm'
      };
    });
  }

  // Generate calendar links for all major platforms
  generateCalendarLinks(event: CalendarEvent) {
    return {
      google: this.generateGoogleCalendarURL(event),
      outlook: this.generateOutlookCalendarURL(event),
      apple: this.generateAppleCalendarURL(event),
      ics: this.generateICS([event])
    };
  }

  // Send calendar event via email (requires backend integration)
  async sendCalendarEventViaEmail(
    event: CalendarEvent, 
    email: string, 
    platform: 'google' | 'outlook' | 'apple' | 'ics' = 'ics'
  ): Promise<boolean> {
    try {
      // This would integrate with your email service
      // For now, we'll simulate the API call
      console.log('Sending calendar event via email:', {
        event: event.title,
        email,
        platform
      });

      // In production, you would make an API call to your backend:
      // const response = await fetch('/api/calendar/send-email', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({ event, email, platform })
      // });
      
      return true;
    } catch (error) {
      console.error('Failed to send calendar event via email:', error);
      return false;
    }
  }
}

// Export singleton instance
export const calendarService = new CalendarService();
export default calendarService;
