# Generated by Django 5.2.1 on 2025-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_can_delete_analytics_user_can_delete_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_operations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_vaccinations',
            field=models.BooleanField(default=False),
        ),
    ]
