# Generated by Django 5.2.7 on 2025-10-12 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='toolusageevent',
            name='analytics_t_country_2d209b_idx',
        ),
        migrations.RemoveIndex(
            model_name='toolusageevent',
            name='analytics_t_device__3709bf_idx',
        ),
        migrations.AddIndex(
            model_name='toolusageevent',
            index=models.Index(fields=['country', 'timestamp'], name='analytics_t_country_ab4570_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusageevent',
            index=models.Index(fields=['device_type', 'timestamp'], name='analytics_t_device__abd176_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusageevent',
            index=models.Index(fields=['action', 'timestamp'], name='analytics_t_action_f063d6_idx'),
        ),
    ]
