# Generated by Django 5.2.1 on 2025-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('MICRO', 'Micro Enterprise'), ('SMALL', 'Small Enterprise'), ('MEDIUM', 'Medium Enterprise')], max_length=10)),
                ('sector', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('SERVICES', 'Services'), ('TRADE', 'Trade'), ('AGRICULTURE', 'Agriculture'), ('CONSTRUCTION', 'Construction'), ('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('investment_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('business_description', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('opportunities', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'MSME',
                'verbose_name_plural': 'MSMEs',
                'ordering': ['-created_at'],
            },
        ),
    ]
