# Generated by Django 5.2.1 on 2025-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_msme_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='second_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='third_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='top_skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
