# Generated by Django 5.2.1 on 2025-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_supportrequest_latitude_supportrequest_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
