# Generated by Django 5.2.1 on 2025-06-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_businessgrowthexpert_msmes_supported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
