# Generated by Django 5.2.1 on 2025-06-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_msme_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='msme_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
