# Generated by Django 5.2.1 on 2025-06-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_msme_msme_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessgrowthexpert',
            name='area_of_expertise',
        ),
    ]
