# Generated by Django 5.2.1 on 2025-06-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_businessgrowthexpert_area_of_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='portfolio.msme')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='portfolio.trainingsession')),
            ],
            options={
                'unique_together': {('session', 'msme')},
            },
        ),
    ]
