# Generated by Django 5.2.1 on 2025-07-14 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_trainingtopic_trainingsession_businesses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('transaction_type', models.CharField(choices=[('FUNDING', 'MSME Funding'), ('INVESTMENT', 'Investment'), ('REPAYMENT', 'Loan Repayment'), ('DIVIDEND', 'Dividend Payment'), ('TOKEN_TRANSFER', 'Token Transfer'), ('CONTRACT_DEPLOY', 'Smart Contract Deployment')], max_length=20)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gas_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('block_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('contract_type', models.CharField(choices=[('MSME_FUNDING', 'MSME Funding Contract'), ('INVESTMENT_POOL', 'Investment Pool Contract'), ('ESCROW', 'Escrow Contract'), ('GOVERNANCE', 'Governance Contract')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('owner_address', models.CharField(max_length=42)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('abi', models.JSONField()),
                ('bytecode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('token_type', models.CharField(choices=[('MSME_TOKEN', 'MSME Token'), ('INVESTMENT_TOKEN', 'Investment Token'), ('GOVERNANCE_TOKEN', 'Governance Token'), ('REWARD_TOKEN', 'Reward Token')], max_length=20)),
                ('total_supply', models.DecimalField(decimal_places=8, max_digits=30)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('owner_address', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecentralizedIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=100, unique=True)),
                ('identity_type', models.CharField(choices=[('MSME', 'MSME Identity'), ('INVESTOR', 'Investor Identity'), ('EXPERT', 'Business Expert Identity'), ('VALIDATOR', 'Validator Identity')], max_length=20)),
                ('public_key', models.CharField(max_length=130)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_data', models.JSONField(default=dict)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.businessgrowthexpert')),
                ('msme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.msme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSMEFundingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('funded_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('repaid_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.msme')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.smartcontract')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('min_investment', models.DecimalField(decimal_places=8, max_digits=20)),
                ('max_investment', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.smartcontract')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.token')),
            ],
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.token')),
            ],
            options={
                'unique_together': {('address', 'token')},
            },
        ),
    ]
