# Generated by Django 5.2.1 on 2025-10-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('age_days', models.PositiveIntegerField(help_text='Age of birds in days when vaccination should be given')),
                ('route', models.CharField(choices=[('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('drinking_water', 'Drinking Water'), ('spray', 'Spray'), ('eye_drop', 'Eye Drop'), ('wing_web', 'Wing Web'), ('hatchery', 'Hatchery')], max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_dosage_used', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_plans', to='operations.poultryoperation')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='vaccinations.vaccinationplan')),
            ],
            options={
                'verbose_name': 'Vaccination Plan',
                'verbose_name_plural': 'Vaccination Plans',
                'ordering': ['scheduled_date', 'age_days'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('calendar', 'Calendar')], max_length=20)),
                ('days_before', models.PositiveIntegerField(help_text='Days before vaccination to send reminder')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vaccination_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vaccinations.vaccinationplan')),
            ],
            options={
                'verbose_name': 'Vaccination Reminder',
                'verbose_name_plural': 'Vaccination Reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poultry_type', models.CharField(choices=[('broilers', 'Broilers'), ('layers', 'Layers'), ('sasso_kroilers', 'Sasso/Kroilers'), ('local', 'Local')], max_length=20)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('age_days', models.PositiveIntegerField()),
                ('route', models.CharField(choices=[('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('drinking_water', 'Drinking Water'), ('spray', 'Spray'), ('eye_drop', 'Eye Drop'), ('wing_web', 'Wing Web'), ('hatchery', 'Hatchery')], max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaccination Template',
                'verbose_name_plural': 'Vaccination Templates',
                'ordering': ['poultry_type', 'age_days'],
                'unique_together': {('poultry_type', 'vaccine_name', 'age_days')},
            },
        ),
    ]
