# Generated by Django 5.2.1 on 2025-10-08 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Mortality rate percentage', max_digits=5)),
                ('feed_conversion_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_daily_gain', models.DecimalField(blank=True, decimal_places=2, help_text='Grams per day', max_digits=5, null=True)),
                ('total_feed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_medication_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_other_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoultryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=200)),
                ('poultry_type', models.CharField(choices=[('broilers', 'Broilers'), ('layers', 'Layers'), ('sasso_kroilers', 'Sasso/Kroilers'), ('local', 'Local')], max_length=20)),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.DateField()),
                ('expected_sale_date', models.DateField(blank=True, null=True)),
                ('number_of_birds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_age_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poultry Operation',
                'verbose_name_plural': 'Poultry Operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
