# Generated by Django 5.2.1 on 2025-10-08 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(choices=[('poultry', 'Poultry Medicine'), ('general', 'General Practice'), ('surgery', 'Surgery'), ('pathology', 'Pathology'), ('nutrition', 'Nutrition'), ('reproduction', 'Reproduction'), ('emergency', 'Emergency Care')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('emergency_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='veterinarians/')),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarians',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('routine', 'Routine Checkup'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('diagnosis', 'Diagnosis'), ('treatment', 'Treatment Plan'), ('follow_up', 'Follow-up')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='operations.poultryoperation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='veterinarians.veterinarian')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='UserVeterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('primary', 'Primary Veterinarian'), ('consultant', 'Consultant'), ('emergency', 'Emergency Contact'), ('specialist', 'Specialist')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarians', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='veterinarians.veterinarian')),
            ],
            options={
                'verbose_name': 'User Veterinarian Relationship',
                'verbose_name_plural': 'User Veterinarian Relationships',
                'unique_together': {('user', 'veterinarian', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='VeterinarianReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('professionalism_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='veterinarians.consultation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian_reviews', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='veterinarians.veterinarian')),
            ],
            options={
                'verbose_name': 'Veterinarian Review',
                'verbose_name_plural': 'Veterinarian Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'veterinarian', 'consultation')},
            },
        ),
    ]
