import React from "react";
import { Button } from "@mui/material";
import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../assets/logo.png";

type VaccineEntry = {
    age: string;
    vaccine: string;
    route: string;
    notes: string;
    date?: string;
};

interface PdfDownloaderProps {
    data: VaccineEntry[];
    type: string;
    arrivalDate: string;
    saleDate: string;
}

const PdfDownloader: React.FC<PdfDownloaderProps> = ({
    data,
    type,
    arrivalDate,
    saleDate,
}) => {
    const downloadPdf = () => {
        const doc = new jsPDF();

        // Add logo
        const img = new Image();
        img.src = logo;
        doc.addImage(img, "PNG", 10, 10, 30, 30);

        // Title
        doc.setFontSize(18);
        doc.setTextColor(40, 100, 60);
        doc.text("Vaccination Planner Report", 50, 20);

        // Subtitle with info
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Chicken Type: ${type.toUpperCase()}`, 50, 30);
        doc.text(`Arrival Date: ${arrivalDate}`, 50, 37);
        doc.text(`Estimated Sale/Stop Date: ${saleDate}`, 50, 44);

        // Table
        const tableData = data.map((v) => [
            v.age,
            v.vaccine,
            v.route,
            v.notes,
            v.date || "",
        ]);

        (doc as any).autoTable({
            head: [["Age/Time", "Vaccine", "Route", "Notes", "Date"]],
            body: tableData,
            startY: 55,
            styles: { fontSize: 10, cellPadding: 3 },
            headStyles: { fillColor: [99, 143, 101] },
        });

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(
            "Generated by Tools - Helping farmers vaccinate smarter and profit more!",
            10,
            doc.internal.pageSize.height - 10
        );

        doc.save(`Vaccination-${type}-${arrivalDate}.pdf`);
    };

    return (
        <Button
            variant="contained"
            color="success"
            onClick={downloadPdf}
            sx={{ mt: 2 }}
        >
            Download PDF
        </Button>
    );
};

export default PdfDownloader;
