# Generated by Django 5.2.1 on 2025-10-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0002_vaccinationreminder_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationreminder',
            name='days_before',
            field=models.IntegerField(help_text='Days before vaccination to send reminder (negative for after vaccination)'),
        ),
    ]
